spring:
  application:
    name: Backend
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/host-usach}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8081/realms/host-usach/protocol/openid-connect/certs}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bda_lab1}
    username: ${SPRING_DATASOURCE_USERNAME:bda_user}
    password: ${SPRING_DATASOURCE_PASSWORD:}

# Configuración personalizada de CORS
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
  allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
  allowed-headers: ${CORS_ALLOWED_HEADERS:Authorization,Content-Type}
  allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
