-- El procedimiento provision_instance(ip, instance_id) fue removido.
-- La lógica equivalente (marcar Ip.Assigned = TRUE + crear Ticket inicial) se
-- ejecuta directamente en InstanceService.createInstance, después del insert
-- Mongo y antes de retornar al cliente. Ver Backend/.../Services/InstanceService.java.