-- Los triggers asociados a "Instance" fueron removidos porque la entidad
-- ahora vive en MongoDB. La lógica equivalente se portó al service layer
-- (Backend/.../Services/InstanceService.java + QuotaService.java):
--
--   trg_check_quota            → client_quotas en Mongo (patrón contador)
--   trg_release_ip             → InstanceService.updateStateByid (UPDATE Ip.Assigned)
--   trg_calculate_active_hours → InstanceService.updateStateByid (inc activeHoursSeconds)
--   trg_check_datacenter_distance → InstanceService.validateDistance (PostGIS query)
--
-- Los triggers que quedan activos se reducen a los de tablas no migradas.
-- Si los necesitas de vuelta (p. ej. para auditar cambios en Users), defínelos
-- aquí. Mantener este archivo vacío evita errores de "missing file" en pipelines
-- que esperan el recurso.